// Static demo build of the Autumn PM interview assistant.
// No backend: window.fetch is shimmed to serve canned data so all the original
// render logic runs unchanged. Write actions (generate / save / upload / search)
// return a friendly "this is a static demo" message.

const DEMO = window.AUTUMN_DEMO_DATA;

const DEMO_WRITE_MESSAGE = "这是静态 Demo：本次操作只读展示，未保存、未联网、未调用模型；保存、真实搜索和 AI 处理需要在完整版中体验。";

// Route /api/* to canned data. Any write (non-GET) returns the demo message.
window.fetch = async (url, options = {}) => {
  const method = (options.method || 'GET').toUpperCase();
  const path = String(url).split('?')[0];
  const json = (body, status = 200) => new Response(JSON.stringify(body), { status, headers: { 'Content-Type': 'application/json' } });

  // These POST endpoints serve canned data so the demo can showcase the feature.
  if (path === '/api/extract-jd') return json({ ok: true, demo_only: true, analysis: DEMO.jdAnalysis });
  if (path === '/api/note-questions') return json({ ok: true, demo_only: true, questions: DEMO.noteQuestions, research_meta: { provided_count: DEMO.agentResult.collected.length, approved_count: 0, mode: 'jd_and_research', note: '公开线索只影响追问方向，不进入本场表现证据。' } });
  if (path === '/api/research/discover') return json({ ok: true, demo_only: true, candidates: DEMO.agentResult.collected, search_meta: { ...DEMO.agentResult.search_meta, demo_only: true } });
  if (path === '/api/research/agent') return json({ ok: true, demo_only: true, collected: DEMO.agentResult.collected, persisted: null, assessed: [], skipped: DEMO.agentResult.skipped || [], trace: DEMO.agentResult.trace, stop_reason: DEMO.agentResult.stop_reason, found_enough: DEMO.agentResult.found_enough, search_meta: { ...DEMO.agentResult.search_meta, demo_only: true } });
  if (path === '/api/growth-report') return json({ ok: true, demo_only: true, report: DEMO.growthReport, memory: DEMO.memory });

  if (method !== 'GET') {
    return json({ ok: false, error: DEMO_WRITE_MESSAGE }, 403);
  }
if (path === '/api/recovery') return json({ ok: true, recovery: { status: 'ok', recovery_required: false, marker: null, issues: [] } });
if (path === '/api/health') return json({ ok: true, provider: 'gemini', model: 'gemini-3.1-flash-lite', active_provider: 'gemini', providers: ['gemini'], demo_mode: true, can_write: false, data_status: { status: 'ok', recovery_required: false } });
  if (path === '/api/interviews') return json({ ok: true, interviews: [DEMO.interviewSummary] });
  if (path === `/api/interviews/${DEMO.interview.id}`) return json({ ok: true, interview: DEMO.interview });
  if (path === '/api/resumes') return json({ ok: true, resumes: [DEMO.resumeSummary] });
  if (path === `/api/resumes/${DEMO.resume.id}`) return json({ ok: true, resume: DEMO.resume });
  if (path === '/api/research') return json({ ok: true, research: [DEMO.research], stats: { total: 1, usable: 0, needs_review: 1 } });
  if (path === `/api/research/${DEMO.research.id}`) return json({ ok: true, research: DEMO.research });
  if (path === '/api/growth-memory') return json({ ok: true, memory: DEMO.memory });
  if (path === '/api/skills') return json({ ok: true, skills: DEMO.skills });
  return json({ ok: false, error: '静态演示中没有这个接口。' }, 404);
};

// ---- Original app logic below (unchanged) ----
const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];
const interviewForm = $('#interview-form');
const interviewFields = ['company', 'role', 'round_name', 'date', 'status', 'outcome', 'job_description', 'resume_context', 'transcript', 'personal_notes'];
const app = { selectedId: null, current: null, interviews: [], resumes: [], research: [], researchCandidates: [], resumeId: '', jdAnalysis: null, selectedAudio: null, selectedResumeFile: null, editingResumeId: null, editingResearchId: null, noteQuestions: [] };
const ACCESS_TOKEN_KEY = 'autumn-assistant-access-token';
function provenanceLabel(value) { return ({ auto_fetched_unverified: '自动读取 · 未人工确认', manual_check_required: '需人工打开 / 摘录', citation_verified: '搜索引用已核对' })[value] || '来源状态未知'; }
const renderResearchListWithProvenance = renderResearchList;
renderResearchList = () => { renderResearchListWithProvenance(); $$('#research-list .research-item').forEach((card, index) => { const badge = document.createElement('span'); badge.className = 'provenance-badge'; badge.textContent = provenanceLabel(app.research[index]?.provenance_status); card.querySelector('.status-badge')?.after(badge); }); };

async function api(url, options = {}) {
  const response = await fetch(url, { headers: { 'Content-Type': 'application/json', ...accessHeaders(), ...(options.headers || {}) }, ...options });
  const data = await response.json();
  if (response.status === 401) throw Error('需要访问口令。');
  if (!response.ok || !data.ok) throw Error(data.error || '请求没有完成。');
  return data;
}
function accessHeaders() { const token = sessionStorage.getItem(ACCESS_TOKEN_KEY); return token ? { 'X-App-Token': token } : {}; }
function toast(message) { const box = $('#toast'); box.textContent = message; box.hidden = false; clearTimeout(toast.timer); toast.timer = setTimeout(() => box.hidden = true, 5000); }
function busy(button, isBusy, label) { button.disabled = isBusy; button.textContent = isBusy ? label : button.dataset.label; }
function field(name) { return interviewForm.elements.namedItem(name); }
const SENSITIVE_PATTERNS = [
  ['手机号', /(?:\+?86[-\s]?)?1[3-9]\d{9}/],
  ['邮箱地址', /[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}/],
  ['身份证号', /\b\d{17}[\dXx]\b/],
];
function updateSensitiveWarning() {
  const warning = $('#sensitive-warning');
  if (!warning) return;
  const material = ['job_description', 'resume_context', 'transcript', 'personal_notes']
    .map(name => field(name)?.value || '').join('\n');
  const labels = SENSITIVE_PATTERNS.filter(([, pattern]) => pattern.test(material)).map(([label]) => label);
  warning.hidden = !labels.length;
  warning.textContent = labels.length
    ? `可能包含敏感信息：检测到${labels.join('、')}。请发送前自行删减；此提示不代表完整脱敏。`
    : '';
}
function setView(viewId) { $$('.view').forEach(view => view.classList.toggle('active', view.id === viewId)); $$('.nav-button').forEach(button => button.classList.toggle('active', button.dataset.view === viewId)); const titles = { 'review-view': '面试复盘', 'research-view': '面经资料库', 'growth-view': '阶段成长报告', 'resume-view': '简历库' }; $('#page-title').textContent = viewId === 'review-view' && app.current ? `${app.current.company} · ${app.current.role}` : titles[viewId]; $('#top-eyebrow').textContent = viewId === 'review-view' ? 'INTERVIEW REVIEW WORKSPACE · V3' : 'AUTUMN PM COACH · V3'; }
function interviewPayload() { const data = Object.fromEntries(interviewFields.map(name => [name, field(name).value])); const resume = app.resumes.find(item => item.id === app.resumeId); return { ...data, outcome_source: data.outcome ? 'self_reported' : '', resume_id: app.resumeId, resume_name: resume?.name || app.current?.resume_name || '', jd_analysis: app.jdAnalysis, research_context: app.researchCandidates }; }

function renderInterviewList() { const list = $('#interview-list'); list.replaceChildren(); $('#interview-total').textContent = app.interviews.length; if (!app.interviews.length) { list.innerHTML = '<p class="empty-copy">还没有面试档案。</p>'; return; } app.interviews.forEach(item => { const button = document.createElement('button'); button.type = 'button'; button.className = `interview-item ${item.id === app.selectedId ? 'active' : ''}`; button.innerHTML = `<strong></strong><span></span>`; button.querySelector('strong').textContent = `${item.company} · ${item.role}`; button.querySelector('span').textContent = `${item.round_name || '面试'} · ${item.date || '未填写日期'}${item.has_review ? ' · 已复盘' : ''}`; button.onclick = () => loadInterview(item.id); list.append(button); }); }
function renderMetrics() { $('#metric-total').textContent = app.interviews.length; $('#metric-actions').textContent = app.interviews.reduce((sum, item) => sum + item.open_actions, 0); $('#metric-reviews').textContent = app.interviews.filter(item => item.has_review).length; const usable = app.research.filter(item => item.status === 'approved').length; $('#metric-research').textContent = usable; $('#research-nav-count').textContent = usable; }
async function refreshInterviews() { app.interviews = (await api('/api/interviews')).interviews; renderInterviewList(); renderMetrics(); }
async function refreshResumes() { app.resumes = (await api('/api/resumes')).resumes; const select = $('#resume-select'); const old = app.resumeId; select.replaceChildren(new Option('暂不关联简历', '')); app.resumes.forEach(item => select.add(new Option(`${item.name}${item.target_role ? ' · ' + item.target_role : ''}`, item.id))); select.value = old; renderResumeList(); }
async function refreshResearch() { const data = await api('/api/research'); app.research = data.research; $('#research-total').textContent = data.stats.total; $('#research-usable').textContent = data.stats.usable; $('#research-review').textContent = data.stats.needs_review; renderResearchList(); renderMetrics(); }

function resetInterview() { app.selectedId = null; app.current = null; app.resumeId = ''; app.jdAnalysis = null; app.researchCandidates = []; app.selectedAudio = null; app.noteQuestions = []; renderNoteQuestions([]); renderJdResearch({ candidates: [] }); interviewFields.forEach(name => field(name).value = name === 'status' ? '待复盘' : ''); $('#resume-select').value = ''; $('#resume-preview').textContent = '选择一份简历；保存面试时会记录当时的内容快照。'; $('#jd-analysis').hidden = true; $('#audio-state').textContent = '尚未选择录音'; $('#consent-check').checked = false; $('#redact-company').checked = false; $('#page-title').textContent = '新建一场面试复盘'; updateSensitiveWarning(); setSaveState('未保存'); setReviewState('等待资料'); renderReview(null); renderInterviewList(); setView('review-view'); }
function setSaveState(text, kind = '') { $('#save-state').textContent = text; $('#save-state').className = `save-state ${kind}`; }
function setReviewState(text, kind = '') { $('#review-state').textContent = text; $('#review-state').className = `review-state ${kind}`; }
function fillInterview(record) { interviewFields.forEach(name => field(name).value = record?.[name] || ''); app.resumeId = record?.resume_id || ''; app.jdAnalysis = record?.jd_analysis || null; app.researchCandidates = record?.research_context || []; $('#resume-select').value = app.resumeId; updateSensitiveWarning(); renderJd(); renderJdResearch({ candidates: app.researchCandidates }); $('#resume-preview').textContent = record?.resume_name ? `已关联：${record.resume_name}。此场面试已保存当时的简历快照。` : '暂未关联简历。'; }
async function loadInterview(id) { try { app.current = (await api(`/api/interviews/${id}`)).interview; app.selectedId = id; fillInterview(app.current); $('#page-title').textContent = `${app.current.company} · ${app.current.role}`; setSaveState('已保存', 'saved'); setReviewState(app.current.review ? '已生成' : '等待复盘', app.current.review ? 'ready' : ''); renderReview(app.current.review); renderInterviewList(); setView('review-view'); } catch (error) { toast(error.message); } }
async function saveInterview() { toast(DEMO_WRITE_MESSAGE); throw Error(DEMO_WRITE_MESSAGE); }

function reviewSection(title) { const section = document.createElement('section'); section.className = 'review-section'; const heading = document.createElement('h4'); heading.textContent = title; section.append(heading); return section; }
function renderCoachItems(root, title, items, detailKey) { if (!items?.length) return; const section = reviewSection(title); const grid = document.createElement('div'); grid.className = 'coach-grid'; items.forEach(item => { const card = document.createElement('article'); card.className = 'coach-item'; card.innerHTML = '<strong></strong><p class="evidence"></p><p class="detail"></p>'; card.querySelector('strong').textContent = item.title || '观察项'; card.querySelector('.evidence').textContent = `证据：${item.evidence || '未提供'}`; card.querySelector('.detail').textContent = item[detailKey] || ''; grid.append(card); }); section.append(grid); root.append(section); }
function renderShortTermMemory(review) { const section = reviewSection('本场短期记忆'); const card = document.createElement('div'); card.className = 'memory-callout'; card.innerHTML = '<strong></strong><p></p><span></span>'; const summary = review.score_summary || {}; card.querySelector('strong').textContent = summary.priority_skills?.length ? `优先训练：${summary.priority_skills.join('、')}` : '本场训练重点'; card.querySelector('p').textContent = review.follow_up || '把本场证据转成下一次可验收的练习。'; card.querySelector('span').textContent = `本场保留：${review.action_plan?.length || 0} 个行动 · 评分只表示训练优先级`; section.append(card); return section; }
function renderScoreSummary(review) {
  const summary = review.score_summary || {}; const quality = review.review_quality || {}; const card = document.createElement('section'); card.className = 'score-summary'; card.innerHTML = '<div class="score-summary-main"><span class="eyebrow">COACHING SIGNAL</span><strong></strong><span></span></div><div class="score-summary-stats"><div><span>证据覆盖</span><strong></strong></div><div><span>诊断置信度</span><strong></strong></div><div><span>训练阶段</span><strong></strong></div></div><p class="score-summary-note"></p><p class="score-summary-provenance"></p>'; card.querySelector('.score-summary-main strong').textContent = summary.coach_score != null ? `${summary.coach_score}/100` : '待生成'; card.querySelector('.score-summary-main span:last-child').textContent = summary.training_band || '训练信号'; card.querySelector('.score-summary-stats div:nth-child(1) strong').textContent = `${Math.round((quality.evidence_coverage || 0) * 100)}%`; card.querySelector('.score-summary-stats div:nth-child(2) strong').textContent = quality.confidence || '未知'; card.querySelector('.score-summary-stats div:nth-child(3) strong').textContent = summary.priority_skills?.length ? `优先补强 ${summary.priority_skills.length} 项` : '暂无优先项'; card.querySelector('.score-summary-note').textContent = quality.data_quality || '评分仅用于训练优先级，不代表录用判断。'; const scoredBy = review.scored_by || {}; card.querySelector('.score-summary-provenance').textContent = `评分记录：${scoredBy.provider || '历史未知'} / ${scoredBy.model || '模型未知'} · Prompt ${scoredBy.prompt_version || '历史未知'} · ${scoredBy.scored_at || '时间未知'}`; return card;
}
function renderBasicSkillCard(skill) {
  const card = document.createElement('article'); card.className = 'skill-score'; card.innerHTML = '<div class="skill-score-head"><div><strong></strong><small></small></div><span></span></div><p class="evidence"></p><p class="skill-diagnosis-copy"></p><details><summary>展开评分依据</summary><div class="dimension-list"></div><div class="skill-gap-list"></div><div class="practice-plan"></div></details>'; card.querySelector('.skill-score-head strong').textContent = skill.skill_name || skill.skill_id || 'PM 能力'; card.querySelector('.skill-score-head small').textContent = `${skill.confidence || '未知'} 置信度 · 覆盖 ${Math.round((skill.evidence_coverage || 0) * 100)}%`; card.querySelector('.skill-score-head > span').textContent = skill.score == null ? '未评分' : `${skill.score}/5`; card.querySelector('.evidence').textContent = `证据：${skill.evidence || '未提供'}`; card.querySelector('.skill-diagnosis-copy').textContent = skill.diagnosis || '暂无诊断。'; const dimensions = card.querySelector('.dimension-list'); (skill.dimensions || []).forEach(dimension => { const row = document.createElement('div'); row.className = 'dimension-row'; row.innerHTML = '<div><strong></strong><span></span></div><p></p><small></small>'; row.querySelector('strong').textContent = dimension.label || dimension.id; row.querySelector('span').textContent = dimension.score == null ? '未展示' : `${dimension.score}/5`; row.querySelector('p').textContent = `状态：${dimension.status || 'unknown'} · ${dimension.rationale || ''}`; row.querySelector('small').textContent = `证据：${dimension.evidence || '未提供'}`; dimensions.append(row); }); const gaps = card.querySelector('.skill-gap-list'); (skill.gaps || []).forEach(gap => { const item = document.createElement('p'); item.textContent = `缺口 ${gap.severity || 'medium'}：${gap.impact || gap.gap_id} · 证据：${gap.evidence || '未提供'}`; gaps.append(item); }); const plan = skill.practice_plan || {}; if (plan.action || plan.prompt || plan.success_criteria?.length) { const practice = card.querySelector('.practice-plan'); practice.innerHTML = '<strong>下一步训练</strong><p></p><ul></ul><small></small>'; practice.querySelector('p').textContent = plan.prompt ? `${plan.action || '训练'}：${plan.prompt}` : (plan.action || skill.next_practice || '补充一轮练习'); (plan.success_criteria || []).forEach(item => { const li = document.createElement('li'); li.textContent = item; practice.querySelector('ul').append(li); }); practice.querySelector('small').textContent = plan.follow_up_question ? `下一条追问：${plan.follow_up_question}` : ''; } return card;
}
function renderSkillCard(skill) { const card = renderBasicSkillCard(skill); const profile = document.createElement('div'); profile.className = 'evidence-profile'; const labels = { specificity: '具体性', ownership: '个人归因', causality: '因果验证', result_quality: '结果质量', reflection: '复盘迁移', probe_resilience: '追问韧性' }; profile.textContent = `证据剖面：${Object.entries(labels).map(([key, label]) => `${label} ${skill.evidence_profile?.[key] ?? 0}/3`).join(' · ')}`; card.querySelector('.skill-diagnosis-copy').after(profile); return card; }

function renderJd() { const root = $('#jd-analysis'); root.replaceChildren(); if (!app.jdAnalysis) { root.hidden = true; return; } root.hidden = false; const title = document.createElement('strong'); title.textContent = app.jdAnalysis.role_title || '岗位画像'; root.append(title); [['职责', 'responsibilities'], ['要求', 'requirements'], ['关键词', 'keywords'], ['可能追问', 'interview_focus'], ['搜索主题', 'search_topics']].forEach(([label, key]) => { if (!app.jdAnalysis[key]?.length) return; const group = document.createElement('div'); group.innerHTML = '<span></span><ul></ul>'; group.querySelector('span').textContent = label; app.jdAnalysis[key].forEach(item => { const li = document.createElement('li'); li.textContent = item; group.querySelector('ul').append(li); }); root.append(group); }); }

// Keep the static fixture aligned with the dynamic diagnostic sections.
function renderReview(review) {
  const root = $('#review-content'); root.replaceChildren(); root.hidden = !review; $('#review-empty').hidden = !!review; if (!review) return;
  root.append(renderScoreSummary(review)); root.append(renderShortTermMemory(review));
  const summary = document.createElement('div'); summary.className = 'review-summary'; summary.textContent = review.summary || ''; root.append(summary);
  renderCoachItems(root, '表现亮点', review.strengths, 'why_it_worked'); renderCoachItems(root, '需要补强', review.gaps, 'improvement');
  if (review.skill_diagnosis?.length) { const section = reviewSection('PM 能力诊断'); const grid = document.createElement('div'); grid.className = 'skill-score-grid'; review.skill_diagnosis.forEach(skill => grid.append(renderSkillCard(skill))); section.append(grid); root.append(section); }
  if (review.questions?.length) { const section = reviewSection('逐题复盘'); const list = document.createElement('div'); list.className = 'question-list'; review.questions.forEach(question => { const card = document.createElement('article'); card.className = 'question-item'; card.innerHTML = '<div class="question-top"><strong></strong><span class="score"></span></div><p class="answer"></p><p class="evidence"></p><p class="assessment"></p><p class="question-meta"></p><p class="next"></p>'; card.querySelector('strong').textContent = question.question; card.querySelector('.score').textContent = `${question.score}/5`; card.querySelector('.answer').textContent = question.answer_summary || ''; card.querySelector('.evidence').textContent = `证据：${question.evidence || ''}`; card.querySelector('.assessment').textContent = question.assessment || ''; card.querySelector('.question-meta').textContent = `证据状态：${question.evidence_quality || 'unknown'}`; card.querySelector('.next').textContent = `练习：${question.next_practice || ''}`; list.append(card); }); section.append(list); root.append(section); }
  if (review.action_plan?.length) { const section = reviewSection('下一步行动'); const list = document.createElement('div'); list.className = 'action-list'; review.action_plan.forEach(action => { const row = document.createElement('label'); row.className = `action-item ${action.done ? 'done' : ''}`; row.innerHTML = '<input type="checkbox" /><div><strong></strong><span></span></div><b></b>'; row.querySelector('input').checked = !!action.done; row.querySelector('strong').textContent = action.action; row.querySelector('span').textContent = action.reason; row.querySelector('b').textContent = action.priority || '中'; list.append(row); }); section.append(list); root.append(section); }
  if (review.follow_up) { const section = reviewSection('后续建议'); const text = document.createElement('div'); text.className = 'follow-up'; text.textContent = review.follow_up; section.append(text); root.append(section); }
}
function enhanceStaticActionItems(review) { $$('#review-content .action-item').forEach((row, index) => { const action = review.action_plan?.[index]; const content = row.querySelector('div'); if (!action || !content || content.querySelector('.action-verification')) return; const verification = document.createElement('div'); verification.className = 'action-verification'; const criteria = document.createElement('small'); criteria.textContent = action.success_criteria?.length ? `验收标准：${action.success_criteria.join('；')}` : '验收标准：完成后补充下一场验证。'; const nextValidation = document.createElement('small'); nextValidation.textContent = action.next_validation ? `下一场验证：${action.next_validation}` : '下一场验证：尚未填写。'; const progress = action.training_progress || {}; const status = document.createElement('span'); status.textContent = `状态：${action.acceptance_status === 'passed' ? '已通过' : action.acceptance_status === 'needs_retry' ? '需重练' : '待验收'} · 训练闭环：${progress.pre_test ? '前测' : '前测待做'} · ${progress.rewrite ? '重写' : '重写待做'} · ${progress.post_test ? '后测' : '后测待做'}`; const completed = document.createElement('small'); completed.textContent = action.completed_at ? `完成时间：${action.completed_at}` : '完成时间：尚未完成'; const attempts = document.createElement('div'); attempts.className = 'training-attempts'; (action.attempts || []).forEach(attempt => { const item = document.createElement('small'); item.textContent = `${({ pre_test: '前测', rewrite: '重写', post_test: '后测' })[attempt.phase] || attempt.phase}：${attempt.response}`; attempts.append(item); }); verification.append(criteria, nextValidation, status, completed, attempts); content.append(verification); }); }
const renderStaticReviewWithActions = renderReview;
renderReview = review => { renderStaticReviewWithActions(review); if (review) enhanceStaticActionItems(review); };
function renderJdResearch(data) { const root = $('#jd-research-handoff'); const candidates = data?.candidates || []; root.hidden = !candidates.length; if (!candidates.length) return; root.querySelector('strong').textContent = `已按 JD 自动发现 ${candidates.length} 条面经线索`; root.querySelector('span').textContent = 'Agent 已展示查询路径和公开页读取状态；静态演示不联网，候选仍不会直接成为事实证据。'; }
async function extractJd() { const button = $('#extract-jd'); busy(button, true, '解析并搜索演示...'); try { const data = await api('/api/extract-jd', { method: 'POST', body: JSON.stringify({ job_description: field('job_description').value }) }); app.jdAnalysis = data.analysis; app.researchCandidates = DEMO.agentResult.collected || []; renderJd(); renderJdResearch({ candidates: app.researchCandidates }); toast('静态演示：JD 已拆解，并已展示按 JD 自动识别的公开候选资料。'); } catch (error) { toast(error.message); } finally { busy(button, false, ''); } }
function demoWrite() { toast(DEMO_WRITE_MESSAGE); }

const NOTE_TYPE_CLASS = { '命中': 'hit', '补刀': 'gap', '通用': 'common' };
async function ensureJdResearchForQuestions() { const raw = field('job_description').value.trim(); if (raw.length < 30) return; if (!app.jdAnalysis) { await extractJd(); return; } if (!app.researchCandidates.length) { app.researchCandidates = DEMO.agentResult.collected || []; renderJdResearch({ candidates: app.researchCandidates }); } }
async function generateNoteQuestions() { const button = $('#note-questions'); busy(button, true, '正在出题...'); try { await ensureJdResearchForQuestions(); const data = await api('/api/note-questions', { method: 'POST', body: JSON.stringify({ job_description: field('job_description').value, resume_context: field('resume_context').value, jd_analysis: app.jdAnalysis, research_context: app.researchCandidates }) }); app.noteQuestions = data.questions || []; renderNoteQuestions(app.noteQuestions, data.research_meta); } catch (error) { toast(error.message); } finally { busy(button, false, ''); } }
function renderNoteQuestions(questions, researchMeta = null) { const panel = $('#note-questions-panel'); panel.replaceChildren(); panel.hidden = !questions.length; if (!questions.length) return; const meta = document.createElement('p'); meta.className = 'note-research-meta'; const count = Number(researchMeta?.provided_count || 0); const approved = Number(researchMeta?.approved_count || 0); meta.textContent = count ? `研究上下文：已参考 ${count} 条公开线索，其中 ${approved} 条人工确认可引用。${researchMeta?.note || '公开线索只影响追问方向，不进入本场表现证据。'}` : (researchMeta?.note || '未获取到公开研究线索，本次问题仅基于 JD 与简历。'); panel.append(meta); questions.forEach(q => { const card = document.createElement('article'); card.className = 'note-question'; card.dataset.id = q.id; card.innerHTML = '<div class="note-question-head"><span class="note-badge"></span><strong></strong></div><p class="note-why"></p><textarea rows="2" placeholder="趁记忆新鲜，简短记下..."></textarea>'; const badge = card.querySelector('.note-badge'); badge.textContent = q.type || '问题'; badge.classList.add(NOTE_TYPE_CLASS[q.type] || 'common'); card.querySelector('strong').textContent = q.question; const researchBasis = q.research_basis?.length ? ` · 公开线索：${q.research_basis.join('；')}` : ''; card.querySelector('.note-why').textContent = q.why_asked ? `为什么问：${q.why_asked}${researchBasis}` : researchBasis; panel.append(card); }); const actions = document.createElement('div'); actions.className = 'note-questions-actions'; const merge = document.createElement('button'); merge.type = 'button'; merge.className = 'secondary-button compact-button'; merge.textContent = '把问答整理进转写'; merge.onclick = collectNoteAnswersIntoTranscript; actions.append(merge); panel.append(actions); }
function collectNoteAnswersIntoTranscript() { const blocks = []; $$('#note-questions-panel .note-question').forEach(card => { const answer = card.querySelector('textarea').value.trim(); if (!answer) return; const question = card.querySelector('strong').textContent; blocks.push(`Q: ${question}\nA: ${answer}`); }); if (!blocks.length) { toast('先填写至少一个回答，再并入转写。'); return; } const transcript = field('transcript'); const addition = `【面后速记】\n${blocks.join('\n\n')}`; transcript.value = transcript.value.trim() ? `${transcript.value.trim()}\n\n${addition}` : addition; updateSensitiveWarning(); setSaveState('有未保存修改'); toast('已并入转写，可继续补充或生成复盘。'); }

function renderResumeList() { const list = $('#resume-list'); list.replaceChildren(); if (!app.resumes.length) { list.innerHTML = '<p class="empty-copy">还没有简历版本。</p>'; return; } app.resumes.forEach(item => { const button = document.createElement('button'); button.type = 'button'; button.className = `interview-item ${item.id === app.editingResumeId ? 'active' : ''}`; button.innerHTML = '<strong></strong><span></span>'; button.querySelector('strong').textContent = item.name; button.querySelector('span').textContent = item.target_role || '未填写目标岗位'; button.onclick = () => loadResume(item.id); list.append(button); }); }
function resetResume() { app.editingResumeId = null; app.selectedResumeFile = null; ['resume-name', 'resume-target', 'resume-content'].forEach(id => $(`#${id}`).value = ''); $('#resume-file').value = ''; $('#resume-file-consent').checked = false; $('#resume-file-state').textContent = '尚未选择文件'; renderResumeList(); }
async function loadResume(id) { try { const resume = (await api(`/api/resumes/${id}`)).resume; app.editingResumeId = id; $('#resume-name').value = resume.name; $('#resume-target').value = resume.target_role; $('#resume-content').value = resume.content; renderResumeList(); setView('resume-view'); } catch (error) { toast(error.message); } }
async function selectResume() { app.resumeId = $('#resume-select').value; if (!app.resumeId) { field('resume_context').value = ''; updateSensitiveWarning(); $('#resume-preview').textContent = '暂未关联简历。'; return; } try { const resume = (await api(`/api/resumes/${app.resumeId}`)).resume; field('resume_context').value = resume.content; updateSensitiveWarning(); $('#resume-preview').textContent = `已关联：${resume.name}。保存面试时会记录当时的内容快照。`; } catch (error) { toast(error.message); } }

function setResearchState(text, kind = '') { $('#research-state').textContent = text; $('#research-state').className = `save-state ${kind}`; }
function resetResearch() { app.editingResearchId = null; ['research-title', 'research-url', 'research-company', 'research-round', 'research-date', 'research-tags', 'research-source', 'research-comments', 'research-notes'].forEach(id => $(`#${id}`).value = ''); $('#research-platform').value = '牛客'; $('#research-role').value = '产品经理'; setResearchState('新资料'); renderResearchList(); }
function fillResearch(record) { app.editingResearchId = record.id; $('#research-title').value = record.title || ''; $('#research-url').value = record.url || ''; $('#research-platform').value = record.platform || '其他'; $('#research-company').value = record.company || ''; $('#research-role').value = record.role || ''; $('#research-round').value = record.round_name || ''; $('#research-date').value = record.published_date || ''; $('#research-tags').value = record.tags || ''; $('#research-source').value = record.source_text || ''; $('#research-comments').value = record.comments_text || ''; $('#research-notes').value = record.notes || ''; setResearchState(record.status === 'candidate' ? '待预审' : '已入库', record.status === 'candidate' ? '' : 'saved'); }
function statusLabel(status) { return ({ candidate: '候选 · 待预审', auto_approved: 'AI 预审 · 待确认', needs_review: '待人工确认', approved: '人工确认 · 可引用', dismissed: '不使用' })[status] || '未知'; }
function renderResearchList() { const list = $('#research-list'); list.replaceChildren(); if (!app.research.length) { list.innerHTML = '<p class="empty-copy">还没有公开资料。先搜索候选，再摘录原帖正文进行 AI 预审。</p>'; return; } app.research.forEach(record => { const card = document.createElement('article'); card.className = 'research-item'; const assessment = record.assessment || {}; const screening = record.screening || {}; const breakdown = Object.entries(screening.relevance_breakdown || {}).map(([key, value]) => `${key} ${value}`).join(' · '); const leadText = (assessment.question_leads || []).filter(item => item && item.question).slice(0, 2).map(item => item.question).join('；'); card.innerHTML = '<div class="research-top"><div><a target="_blank" rel="noreferrer"></a><p></p></div><div class="badge-row"><span class="status-badge"></span><span class="confidence"></span></div></div><p class="research-summary"></p><p class="research-screening"></p><div class="research-meta"></div><div class="research-actions"></div>'; const link = card.querySelector('a'); link.href = record.url; link.textContent = record.title; card.querySelector('.research-top p').textContent = [record.platform, record.company, record.role, record.round_name, record.published_date].filter(Boolean).join(' · '); const badge = card.querySelector('.status-badge'); badge.textContent = statusLabel(record.status); badge.classList.add(record.status); card.querySelector('.confidence').textContent = record.assessment && record.confidence ? `AI 置信度 ${record.confidence}%` : '仅演示字段'; card.querySelector('.research-summary').textContent = assessment.summary || (record.source_text || '').slice(0, 240) || '未填写摘要'; card.querySelector('.research-screening').textContent = screening.relevance != null ? `相关度提示 ${screening.relevance}/100${breakdown ? ` · ${breakdown}` : ''}` : '相关度尚未计算'; card.querySelector('.research-meta').textContent = assessment.concerns?.length ? `限制：${assessment.concerns.join('；')}${leadText ? ` · 出题线索：${leadText}` : ''}` : `资料仅作为公开经验参考，复盘中会保留原链接与日期。${leadText ? ` 出题线索：${leadText}` : ''}`; const actions = card.querySelector('.research-actions'); const edit = document.createElement('button'); edit.className = 'secondary-button compact-button'; edit.textContent = '查看/编辑'; edit.onclick = () => { fillResearch(record); setView('research-view'); window.scrollTo({ top: 0, behavior: 'smooth' }); }; actions.append(edit); list.append(card); }); }
function renderDiscovery(candidates) { const root = $('#discovery-results'); root.replaceChildren(); if (!candidates.length) { root.innerHTML = '<p class="empty-copy">没有发现候选。已尝试小红书公开搜索，但结果稀疏；建议换同义词、轮次，或手动粘贴原帖链接。</p>'; return; } (candidates || []).forEach(candidate => { const card = document.createElement('article'); card.className = 'discovery-item'; card.innerHTML = '<a target="_blank" rel="noreferrer"></a><p></p><div><span></span><button class="secondary-button compact-button" type="button">带入资料库</button></div>'; const screening = candidate.screening || {}; const breakdown = screening.relevance_breakdown ? Object.entries(screening.relevance_breakdown).map(([key, value]) => `${key} ${value}`).join(' / ') : ''; card.querySelector('a').href = candidate.url; card.querySelector('a').textContent = candidate.title; card.querySelector('p').textContent = `${candidate.summary || '公开搜索候选'}${screening.reason ? ` · ${screening.reason}` : ''}`; card.querySelector('span').textContent = [candidate.platform, candidate.provenance_status || '待人工确认', screening.relevance != null ? `相关度 ${screening.relevance}/100` : '', breakdown].filter(Boolean).join(' · '); card.querySelector('button').onclick = demoWrite; root.append(card); }); }
 function renderSearchMeta(meta) { const root = $('#search-meta'); root.replaceChildren(); root.hidden = !meta; if (!meta) return; const title = document.createElement('strong'); title.textContent = `${meta.platform_label || '全网'} · 已尝试 ${meta.queries_tried?.length || 0} 条查询 · 候选 ${meta.result_count || 0}`; root.append(title); (meta.queries_tried || []).forEach(query => { const item = document.createElement('span'); item.textContent = `查询：${query}`; root.append(item); }); const statuses = Object.entries(meta.fetch_status_counts || {}).map(([status, count]) => `${status} ${count}`).join(' · '); if (statuses) { const item = document.createElement('span'); item.textContent = `公开页读取：${statuses}`; root.append(item); } if (meta.failure_reasons?.length) { const item = document.createElement('span'); item.textContent = `失败说明：${meta.failure_reasons.join('；')}`; root.append(item); } if (meta.demo_only) { const item = document.createElement('span'); item.textContent = '静态演示：以上是预置查询轨迹，未真实联网、读取原帖或写入资料库。'; root.append(item); } if (meta.empty_reason) { const reason = document.createElement('span'); reason.textContent = `结果说明：${meta.empty_reason} 建议换公司别名、岗位同义词或轮次，也可以手动粘贴原帖链接。`; root.append(reason); } }
function researchDiscoveryPayload() { return { company: $('#discover-company').value, role: $('#discover-role').value, round_name: $('#discover-round').value, topic: $('#discover-topic').value, job_description: field('job_description').value, jd_analysis: app.jdAnalysis, platform: $('#discover-platform').value }; }
async function runResearchAgent() { const button = $('#agent-button'); busy(button, true, 'Agent 正在自主调研...'); try { await api('/api/research/agent', { method: 'POST', body: JSON.stringify({ ...researchDiscoveryPayload(), async: true }) }); renderSearchMeta({ platform_label: '静态演示 · Agent 自动收录', result_count: DEMO.agentResult.collected.length }); renderAgentTrace(DEMO.agentResult.trace, DEMO.agentResult.stop_reason, DEMO.agentResult.found_enough); app.researchCandidates = DEMO.agentResult.collected || []; renderAgentCollected(app.researchCandidates); renderJdResearch({ candidates: app.researchCandidates }); } catch (error) { toast(error.message); } finally { busy(button, false, ''); } }
async function discoverResearch(event) { event.preventDefault(); const button = $('#discover-button'); busy(button, true, '公开搜索演示...'); try { const data = await api('/api/research/discover', { method: 'POST', body: JSON.stringify(researchDiscoveryPayload()) }); renderSearchMeta(data.search_meta); renderDiscovery(data.candidates || []); } catch (error) { toast(error.message); } finally { busy(button, false, ''); } }
function renderAgentTrace(trace, stopReason, foundEnough) { const root = $('#agent-trace'); root.replaceChildren(); root.hidden = !(trace && trace.length); if (!trace || !trace.length) return; trace.forEach(step => { const card = document.createElement('div'); card.className = 'agent-round'; card.innerHTML = '<strong></strong><p></p><p class="agent-query"></p>'; const label = step.action === 'stop' ? '停止' : step.action === 'fetch' ? '读取公开页' : '搜索'; card.querySelector('strong').textContent = `第 ${step.round} 轮 · ${label}${step.action === 'search' ? ` · 新增 ${step.added || 0}` : ''}${step.action === 'fetch' ? ` · 读取 ${step.fetched || 0}` : ''}`; card.querySelector('p').textContent = step.reasoning || ''; const q = card.querySelector('.agent-query'); if (step.query) q.textContent = `${step.action === 'fetch' ? '动作' : '查询词'}：${step.query}`; else q.remove(); root.append(card); }); const stop = document.createElement('p'); stop.className = 'agent-stop'; stop.textContent = `${foundEnough ? '已找够待确认资料' : '未达目标数量'} · ${stopReason || '结束'}`; root.append(stop); }
function renderAgentCollected(candidates) { const root = $('#discovery-results'); root.replaceChildren(); if (!candidates.length) { root.innerHTML = '<p class="empty-copy">Agent 未收集到通过来源校验的候选。</p>'; return; } candidates.forEach(candidate => { const card = document.createElement('article'); card.className = 'discovery-item'; card.innerHTML = '<a target="_blank" rel="noreferrer"></a><p></p><div><span></span><button class="secondary-button compact-button" type="button">带入资料库</button></div>'; card.querySelector('a').href = candidate.url; card.querySelector('a').textContent = candidate.title; const screening = candidate.screening || {}; const fetchLabel = candidate.fetch_status === 'fetched_metadata' ? '已自动读取公开页' : candidate.fetch_status === 'shell_only' ? '页面脚本壳' : '仍需人工确认'; card.querySelector('p').textContent = `${candidate.summary || '候选公开资料'}${screening.reason ? ` · 初筛：${screening.reason}` : ''}`; card.querySelector('span').textContent = [candidate.platform, candidate.platform_id ? `来源 ${candidate.platform_id}` : '', screening.relevance != null ? `相关度提示 ${screening.relevance}/100` : '', fetchLabel].filter(Boolean).join(' · '); card.querySelector('button').onclick = demoWrite; root.append(card); }); }

function renderMemory(memory) { const root = $('#memory-summary'); root.replaceChildren(); const items = [{ label: '已复盘面试', value: memory.reviewed_interviews || 0 }, { label: '待完成行动', value: memory.open_actions?.length || 0 }, { label: '重复薄弱点', value: memory.recurring_gaps?.length || 0 }]; items.forEach(item => { const block = document.createElement('div'); block.innerHTML = '<span></span><strong></strong>'; block.querySelector('span').textContent = item.label; block.querySelector('strong').textContent = item.value; root.append(block); }); const patterns = document.createElement('div'); patterns.className = 'memory-patterns'; const generated = document.createElement('span'); generated.textContent = "记忆快照：" + (memory.generated_at || "刚刚计算"); patterns.append(generated); const audit = memory.audit || {}; const auditTag = document.createElement('span'); auditTag.textContent = audit.replayable ? `可回放聚合：${audit.input_count || 0} 场 · ${audit.algorithm_version || 'deterministic'}` : '聚合来源未提供'; patterns.append(auditTag); const comparability = document.createElement('span'); comparability.className = memory.comparability === 'comparable' ? 'memory-ok' : 'memory-warning'; comparability.textContent = memory.comparability === 'comparable' ? '同一评分版本可比较' : `评分可比性：${memory.comparability || '未知'}`; patterns.append(comparability); const label = document.createElement('p'); label.textContent = '当前重复出现'; patterns.append(label); (memory.recurring_gaps || []).slice(0, 4).forEach(item => { const tag = document.createElement('span'); tag.textContent = `${item.title} · ${item.occurrences}次`; patterns.append(tag); }); if (!(memory.recurring_gaps || []).length) patterns.append('暂无足够数据'); const outcome = memory.outcome_signal || {}; const outcomeTag = document.createElement('span'); outcomeTag.textContent = '结果反馈：' + (outcome.sample_count || 0) + ' 场 · 通过 ' + (outcome.passed?.count || 0) + ' / 未通过 ' + (outcome.failed?.count || 0) + ' · ' + (outcome.status || '样本不足'); patterns.append(outcomeTag); const outcomeNote = document.createElement('span'); outcomeNote.textContent = outcome.interpretation || '结果为自报训练反馈，不是招聘预测。'; patterns.append(outcomeNote); root.append(patterns); }
function appendStaticMemorySources(memory) { const root = $('#memory-summary'); if (!(memory.recurring_gaps || []).length) return; const section = document.createElement('section'); section.className = 'memory-governance'; const heading = document.createElement('p'); heading.textContent = '记忆来源（演示）'; section.append(heading); (memory.recurring_gaps || []).forEach(item => { const details = document.createElement('details'); const summary = document.createElement('summary'); summary.textContent = `${item.title} · ${item.occurrences} 次`; details.append(summary); (item.sources || []).forEach(source => { const line = document.createElement('p'); line.className = 'memory-source-line'; line.textContent = `${source.company} · ${source.round_name} · ${source.date} · 证据：${source.evidence}`; details.append(line); }); section.append(details); }); root.append(section); }
const renderStaticMemoryWithSources = renderMemory;
renderMemory = memory => { renderStaticMemoryWithSources(memory); appendStaticMemorySources(memory); };
function renderSkillList(skills) { const root = $('#skill-list'); root.replaceChildren(); skills.forEach(skill => { const item = document.createElement('div'); item.className = 'skill-definition'; item.innerHTML = '<strong></strong><span></span>'; item.querySelector('strong').textContent = skill.name; const anchors = skill.score_anchors || {}; item.querySelector('span').textContent = `${skill.focus} 评分锚点：1 ${anchors['1'] || '未展示'}；3 ${anchors['3'] || '合格'}；5 ${anchors['5'] || '优秀'}`; root.append(item); }); }
function renderStaticGrowthReport(report) { const root = $('#growth-content'); root.replaceChildren(); root.hidden = false; $('#growth-empty').hidden = true; const summary = document.createElement('div'); summary.className = 'review-summary'; summary.textContent = report.summary; root.append(summary); const assessment = reviewSection('长期记忆判断'); const assessmentText = document.createElement('p'); assessmentText.className = 'body-copy'; assessmentText.textContent = report.stage_assessment; assessment.append(assessmentText); root.append(assessment); renderCoachItems(root, '可观察到的变化', report.growth_signals, 'interpretation'); const patterns = reviewSection('重复出现的缺口'); const patternList = document.createElement('div'); patternList.className = 'pattern-list'; (report.recurring_patterns || []).forEach(pattern => { const row = document.createElement('article'); row.innerHTML = '<strong></strong><span></span><p></p><p class="next"></p>'; row.querySelector('strong').textContent = pattern.skill; row.querySelector('span').textContent = `${pattern.occurrences} 次`; row.querySelector('p').textContent = `证据：${pattern.evidence}`; row.querySelector('.next').textContent = pattern.recommendation; patternList.append(row); }); patterns.append(patternList); root.append(patterns); const training = reviewSection('下一步长期训练'); (report.priority_training || []).forEach(item => { const row = document.createElement('article'); row.className = 'coach-item'; row.innerHTML = '<strong></strong><p></p><p class="next"></p>'; row.querySelector('strong').textContent = item.action; row.querySelector('p').textContent = `${item.why_now}${item.source ? ` · 来源：${item.source}` : ''}`; row.querySelector('.next').textContent = `验收标准：${item.success_criterion}`; training.append(row); }); root.append(training); if (report.report_grounding) { const grounding = reviewSection('报告来源'); const groundingText = document.createElement('p'); groundingText.className = 'body-copy'; groundingText.textContent = report.report_grounding.note || '结构化长期记忆提供的报告来源。'; grounding.append(groundingText); root.append(grounding); } const quality = reviewSection('数据边界'); const qualityText = document.createElement('p'); qualityText.className = 'body-copy'; qualityText.textContent = report.data_quality; quality.append(qualityText); root.append(quality); }
async function refreshGrowthMemory() { try { const data = await api('/api/growth-memory'); renderMemory(data.memory); $('#growth-state').textContent = data.memory.reviewed_interviews ? '已有记录' : '等待数据'; } catch (error) { toast(error.message); } }
function demoDataAction() { demoWrite(); }

interviewForm.onsubmit = event => { event.preventDefault(); demoWrite(); };
$('#new-interview').onclick = resetInterview;
$('#load-demo').onclick = () => loadInterview(DEMO.interview.id);
$('#review-button').onclick = demoWrite; $('#extract-jd').onclick = extractJd; $('#open-jd-research').onclick = () => setView('research-view'); $('#transcribe-audio').onclick = demoWrite; $('#resume-select').onchange = selectResume; $('#note-questions').onclick = generateNoteQuestions; $('#delete-interview').onclick = demoWrite; $('#export-data').onclick = demoDataAction; $('#create-backup').onclick = demoDataAction; $('#restore-backup').onclick = demoDataAction; $('#clear-transcripts').onclick = demoDataAction; $('#clear-research').onclick = demoDataAction; $('#retention-preview').onclick = demoDataAction; $('#retention-apply').onclick = demoDataAction;
$('#audio-file').onchange = event => { app.selectedAudio = event.target.files?.[0] || null; $('#audio-state').textContent = app.selectedAudio ? `${app.selectedAudio.name} · ${(app.selectedAudio.size / 1024 / 1024).toFixed(1)} MB` : '尚未选择录音'; };
$('#transcript-file').onchange = async event => { const file = event.target.files?.[0]; if (!file) return; field('transcript').value = await file.text(); updateSensitiveWarning(); };
interviewFields.forEach(name => field(name).addEventListener('input', updateSensitiveWarning));
$('#new-resume').onclick = resetResume; $('#resume-form').onsubmit = event => { event.preventDefault(); demoWrite(); }; $('#resume-file').onchange = event => { app.selectedResumeFile = event.target.files?.[0] || null; $('#resume-file-state').textContent = app.selectedResumeFile ? `${app.selectedResumeFile.name} · ${(app.selectedResumeFile.size / 1024 / 1024).toFixed(1)} MB` : '尚未选择文件'; }; $('#parse-resume-file').onclick = demoWrite;
function showDemoGrowth() { renderStaticGrowthReport(DEMO.growthReport); $('#growth-empty')?.remove(); $('#growth-state').textContent = '演示报告'; toast('静态演示：展示的是合成跨场记忆，不写入真实记录。'); }
$('#research-new').onclick = resetResearch; $('#research-form').onsubmit = event => { event.preventDefault(); demoWrite(); }; $('#discover-form').onsubmit = discoverResearch; $('#agent-button').onclick = runResearchAgent; $('#generate-growth').onclick = showDemoGrowth;
$('#discover-button').textContent = '仅搜索候选预览'; $('#agent-button').textContent = 'Agent 自动调研并收录';
$$('[data-view]').forEach(button => button.onclick = () => setView(button.dataset.view));
$$('button').forEach(button => button.dataset.label = button.textContent);
async function initializeApp() { resetInterview(); const recovery = await api('/api/recovery'); if (recovery.recovery?.recovery_required) { $('#model-status').textContent = '需要恢复本地数据'; $('#data-state').textContent = '数据需要恢复'; $('.status-dot').className = 'status-dot error'; toast('本地数据需要恢复：请先检查备份，再继续使用。'); return; } await Promise.all([refreshResumes(), refreshInterviews(), refreshResearch(), refreshGrowthMemory(), api('/api/skills').then(data => renderSkillList(data.skills))]); try { const data = await api('/api/health'); const demoTag = data.demo_mode && !data.can_write ? ' · 只读演示' : ''; $('#model-status').textContent = `${data.active_provider || 'gemini'} · ${data.model}${demoTag}`; $('.status-dot').className = 'status-dot ready'; } catch { $('#model-status').textContent = '静态演示'; $('.status-dot').className = 'status-dot ready'; } }
(async () => { try { await initializeApp(); await loadInterview(DEMO.interview.id); } catch (error) { toast(error.message); } })();
