// Static-only fixture overrides. Keep these clearly synthetic and never present them as verified posts.
window.AUTUMN_DEMO_DATA = {
  research: {
    id: "r1",
    title: "小红书公开候选（演示资料）",
    url: "https://www.xiaohongshu.com/",
    platform: "小红书",
    platform_id: "xiaohongshu",
    company: "示例公司",
    role: "产品经理",
    round_name: "一面",
    published_date: "",
    tags: "演示, 相关性, 一面",
    status: "needs_review",
    confidence: 0,
    source_kind: "demo_synthetic",
    provenance_status: "manual_check_required",
    search_query: "site:xiaohongshu.com/explore 示例公司 产品经理 一面 指标 面经",
    retrieved_at: "2026-09-05T12:00:00+00:00",
    source_text: "这是静态 Demo 的合成资料卡，用来展示小红书公开搜索候选、相关度拆解和人工确认流程，不对应任何真实原帖。",
    comments_text: "",
    assessment: {
      recommendation: "needs_review",
      confidence: 0,
      summary: "演示合成内容，不对应可验证的原帖；需要人工打开真实链接并摘录正文。",
      claims: [],
      credibility_signals: [],
      concerns: ["演示合成内容", "当前链接不是原帖", "必须人工确认原帖正文"],
      review_reason: "搜索候选不自动进入可信资料库。",
    },
    updated_at: "2026-09-05T12:00:00",
  },
  agentResult: {
    collected: [{
      url: "https://www.xiaohongshu.com/",
      title: "小红书候选资料（演示，待人工打开确认）",
      platform: "小红书",
      platform_id: "xiaohongshu",
      summary: "演示候选：仅用于展示平台限定搜索、相关度分解和来源状态，不是可引用原帖。",
      published_date: "",
      search_query: "site:xiaohongshu.com/explore 字节 产品经理 一面 指标 面经",
      source_kind: "demo_synthetic",
      provenance_status: "manual_check_required",
      screening: {
        recommendation: "needs_review",
        relevance: 72,
        relevance_breakdown: { company_match: 30, role_match: 25, round_match: 10, topic_match: 12, interview_specificity: 0, recency: 0 },
        reason: "岗位和主题命中，但这是演示候选，必须打开原帖确认具体面试内容。",
      },
    }],
    trace: [
      { round: 1, reasoning: "先用平台限定词搜索公司、岗位和轮次", action: "search", query: "site:xiaohongshu.com/explore 字节 产品经理 一面 指标 面经", added: 1 },
      { round: 2, reasoning: "保留待人工确认状态，不把搜索摘要当作证据", action: "stop", stop_reason: "交给人工打开原帖并摘录正文。", added: 0 },
    ],
    stop_reason: "交给人工打开原帖并摘录正文。",
    found_enough: false,
    search_meta: {
      platform: "xiaohongshu",
      platform_label: "小红书",
      queries_tried: ["site:xiaohongshu.com/explore 字节 产品经理 一面 指标 面经", "site:xiaohongshu.com 字节 AI产品 项目深挖"],
      result_count: 1,
      empty_reason: "",
    },
  },
};
